"""
Excel reader for TOK Product Automation.
Reads product data from an Excel spreadsheet.
"""

from pathlib import Path
from typing import Any

import openpyxl


class ProductRow:
    """Represents a single product row from the Excel file."""

    def __init__(self, data: dict[str, Any], row_num: int):
        self.data = data
        self.row_num = row_num

    @property
    def name(self) -> str:
        return str(self.data.get("name", "")).strip()

    @property
    def price(self) -> str:
        raw = self.data.get("price", "0")
        # Handle both numbers and strings from Excel
        if isinstance(raw, (int, float)):
            return str(int(raw))
        return str(raw).strip()

    @property
    def brand(self) -> str:
        return str(self.data.get("brand", "")).strip()

    @property
    def category(self) -> str:
        return str(self.data.get("category", "")).strip()

    @property
    def brand_slug(self) -> str:
        return str(self.data.get("brand_slug", "")).strip()

    @property
    def category_slug(self) -> str:
        return str(self.data.get("category_slug", "")).strip()

    @property
    def origin_price(self) -> str:
        raw = self.data.get("origin_price", "")
        if isinstance(raw, (int, float)):
            return str(int(raw))
        return str(raw).strip()

    @property
    def skin_type(self) -> str | None:
        val = str(self.data.get("skin_type", "")).strip()
        return val if val else None

    @property
    def skin_concern(self) -> str | None:
        val = str(self.data.get("skin_concern", "")).strip()
        return val if val else None

    @property
    def origin_country(self) -> str:
        val = str(self.data.get("origin_country", "korea")).strip()
        return val if val else "korea"

    def is_valid(self) -> tuple[bool, str]:
        """Check if the row has minimum required fields."""
        if not self.name:
            return False, f"Row {self.row_num}: 'name' is required"
        if len(self.name) < 3:
            return (
                False,
                f"Row {self.row_num}: 'name' must be at least 3 characters",
            )
        if not self.price:
            return False, f"Row {self.row_num}: 'price' is required"
        try:
            if float(self.price) <= 0:
                return False, f"Row {self.row_num}: 'price' must be positive"
        except ValueError:
            return False, f"Row {self.row_num}: 'price' must be a number"
        return True, ""

    def __repr__(self) -> str:
        return f"ProductRow({self.name}, price={self.price})"


def read_excel(file_path: str, sheet_name: str = "Sheet1") -> list[ProductRow]:
    """
    Read product data from an Excel file.

    Expected columns (case-insensitive, header row required):
        - name (required): Product name
        - price (required): Product selling price
    
    Note: All other fields (brand, category, origin, etc.) will be generated by AI
    and are not required in the Excel file.

    Returns:
        List of ProductRow objects.
    """
    path = Path(file_path)
    if not path.exists():
        raise FileNotFoundError(f"Excel file not found: {path.resolve()}")

    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)

    if sheet_name not in wb.sheetnames:
        available = ", ".join(wb.sheetnames)
        raise ValueError(
            f"Sheet '{sheet_name}' not found. Available sheets: {available}"
        )

    ws = wb[sheet_name]
    rows = list(ws.iter_rows(values_only=True))

    if not rows or not rows[0]:
        raise ValueError("Excel file is empty or has no header row")

    # Build header mapping (case-insensitive)
    headers_raw = [str(h).strip().lower() if h else "" for h in rows[0]]
    header_map: dict[str, int] = {}
    for i, h in enumerate(headers_raw):
        if h:
            header_map[h] = i

    required = ["name", "price"]
    missing = [col for col in required if col not in header_map]
    if missing:
        raise ValueError(
            f"Missing required columns: {', '.join(missing)}. "
            f"Found columns: {list(header_map.keys())}"
        )

    products: list[ProductRow] = []
    for row_idx, row in enumerate(rows[1:], start=2):
        if all(cell is None or (isinstance(cell, str) and cell.strip() == "") for cell in row):
            continue  # Skip completely empty rows

        data: dict[str, Any] = {}
        for col_name, col_idx in header_map.items():
            if col_idx < len(row):
                val = row[col_idx]
                data[col_name] = val

        product = ProductRow(data, row_idx)
        valid, msg = product.is_valid()
        if valid:
            products.append(product)
        else:
            print(f"  ⚠ Skipping: {msg}")

    wb.close()
    return products
